services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api/v1
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - eco-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/eco_bottle
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=eco-bottle-super-secret-jwt-key-change-in-production-2024
      - JWT_REFRESH_SECRET=eco-bottle-refresh-secret-jwt-key-change-in-production-2024
      - FRONTEND_URL=http://localhost:3000
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=100
      - NODE_CLUSTER=false
      - WORKERS=2
    depends_on:
      - mongo
      - redis
    networks:
      - eco-network
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=eco_bottle
    ports:
      - "27017:27017"
    networks:
      - eco-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - eco-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - eco-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - eco-network
    restart: unless-stopped

networks:
  eco-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  prometheus-data: